apiVersion: apps/v1
kind: Deployment
metadata:
  name: funny-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: funny-app
  template:
    metadata:
      labels:
        app: funny-app
    spec:
      containers:
        - name: funny-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{- range .Values.env }}
              - name: {{ .name }}
                value: "{{ .value }}"
            {{- end }}

            {{- range .Values.envFromSecret }}
              - name: {{ .name }}
                valueFrom:
                  secretKeyRef:
                    name: {{ .secretName }}
                    key: {{ .key }}
            {{- end }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- if .Values.livenessProbe.exec }}
            exec:
              command: {{ toYaml .Values.livenessProbe.exec.command | nindent 4 }}
            {{- else if .Values.livenessProbe.httpGet }}
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 1 }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
          {{- end }}

          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- if .Values.readinessProbe.exec }}
            exec:
              command: {{ toYaml .Values.readinessProbe.exec.command | nindent 4 }}
            {{- else if .Values.readinessProbe.httpGet }}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 1 }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}
          {{- end }}

          volumeMounts:
            - name: gcp-creds
              mountPath: {{ .Values.gcpCredentials.mountPath  }}
              subPath: googlekey.json
      volumes:
        - name: gcp-creds
          secret:
            secretName: {{ .Values.gcpCredentials.secretName }}




