#######################################################
# This file is used to configure common settings for all profiles
#######################################################

# Hibernate - SQL configure
spring:
  threads:
    virtual:
      enabled: ${ENABLED_VIRTUAL_THREAD:true}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER}
    password: ${EMAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/funnyapp
    username: postgres
    password: ${DB_PASS:123456}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT:8081}
#  tomcat:
#    threads:
#      max: 10
#    accept-count: 500
#    connection-timeout: 30000


management:
  endpoint:
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'prometheus', 'metrics']
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http.client.requests: true
        http.server.requests: true
      percentiles:
        http.client.requests: [0.5, 0.95, 0.99]
        http.server.requests: [0.5, 0.95, 0.99]


#  servlet:
#    context-path: /api # App config common
app:
  token-expired: 86400000
  jwt-secret-key: ${JWT_SECRET:12345678901234567890123456789012}
  google-api-key: ${GOOGLE_KEY}
  google-credential-path: ${GOOGLE_CREDENTIAL_PATH:classpath:googlekey.json}
  google-part: snippet,contentDetails,statistics
  gpt-key: ${GPT_KEY}
  use-password-less: true
  domain: 'https://funnyapp.canh-labs.com'
  invite-template: 'templates/email/invite.html'
  chatgpt-url: 'https://api.openai.com/v1/chat/completions'
  youtube-url: 'https://www.googleapis.com/youtube/v3/videos'
  image-url: 'https://image.canh-labs.com'
  main-domain: 'https://canh-labs.com'
  image-storage-path: '/opt/data/images'
  email-setting:
      enable-preview-mode: false
      percentage: 10
      max-daily-emails: 200
      whitelist: ${EMAIL_PREVIEW_WHITELIST:canh@canh-labs.com,@canh-labs.com}
cache:
  type: guava # or "redis"
  mfa:
    ttl-minutes: 5
    max-size: 10000

  default-settings:
    ttl-minutes: 1440 # 24 hours
    max-size: 10000

logging:
  masking:
    fields: [password, token, secret, otp, apiKey, api_key, gptKey, gpt_key, googleApiKey, google_api_key, jwt]

# Springdoc (OpenAPI/Swagger) config
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    # path: /swagger-ui/index.html
    enabled: true
  show-actuator: true



