# values.yaml
namespace: funny-app

replicaCount: 1

image:
  # repository: registry:5000/funny-app
  repository: nguyenhuuca/funny-app
  tag: prod-4
  pullPolicy: IfNotPresent

ingress:
  enabled: false

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: "400m"      # tối thiểu 0.1 CPU
    memory: "1000Mi"  # tối thiểu 256 MB RAM
  limits:
    cpu: "500m"      # tối đa 0.5 CPU
    memory: "600Mi"  # tối đa 512 MB RAM

service:
  type: NodePort
  port: 8081
  targetPort: 8081
  nodePort: 30080

containerPort: 8081
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: JAVA_OPTS
    value: "-Xms256m -Xmx512m"
  - name: DB_USER
    value: "postgres"
  - name: DB_NAME
    value: "funnyapp"
  - name: DB_PASS
    value: "123456"
  - name: DB_HOST
    value: "host.docker.internal"
  - name: GOOGLE_CREDENTIAL_PATH
    value: "/secrets/googlekey.json"

envFromSecret:
  - name: EMAIL_SENDER
    secretName: email-credentials
    key: EMAIL_SENDER
  - name: EMAIL_PASS
    secretName: email-credentials
    key: EMAIL_PASS

livenessProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: 8081
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: 8081
  initialDelaySeconds: 120
  periodSeconds: 5
  timeoutSeconds: 10
  failureThreshold: 10

gcpCredentials:
  secretName: gcp-credentials
  mountPath: /secrets/googlekey.json

