# demo-deploy.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: funny-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funny-app
  template:
    metadata:
      labels:
        app: funny-app
    spec:
      containers:
        - name: funny-app
          image: registry:5000/funny-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: funny-app
  namespace: test
spec:
  type: NodePort
  selector:
    app: funny-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
